var bio = {
    "name": "Yan Ren",
    "role": "\"Not a real programmer\"",
    "welcomeMessage": "",
    "contacts": {
        "email": "ryan.ren3@gmail.com",
        "github": "https://github.com/yan-ren",
        "location": "Montreal, Quebec",
        "linkedin": "https://www.linkedin.com/in/yan-ren-ryan"
    },
    "skills": ["Languages: Java, C/C++, Python, VHDL, MATLAB",
              "OS: Linux",
              "Web: HTML, CSS, JavaScript, jQuery",
              "Tools: Git, SQL and PostgreSQL, TestNG, OpenCV",
              "IDEs: Eclipse, Pycharm, Visual Studio"
            ],
    "bioPic": "./images/yan2.jpg"
};

var education = {
    "schools": [{
        "name": "McGill University",
        "location": "Montreal, Quebec",
        "degree": "Bachelor of Engineering",
        "majors": ["Computer Eng"],
        "dates": "From: 2013 To: 2018",
        "url": "http://"
    }, {
        "name": "Columbia International College",
        "location": "Hamilton, Ontario",
        "degree": "High School Diploma",
        "majors": ["Science", "English"],
        "dates": "From: 2012 To: 2013",
        "url": "#"
    }],
    "onlineCourses": [{
        "title": "Intro to HTML and CSS",
        "school": "Udacity",
        "dates": "2016",
        "url": "http://www.udacity.com"
    }, {
        "title": "JavaScript basics",
        "school": "Udacity",
        "dates": "2017",
        "url": "http://www.sssudacity.com"
    }, {
        "title": "Intro tsSo Database",
        "school": "Stanford Lagunita",
        "dates": "2016",
        "url": "https://lagunita.stanford.edu"
    }]
};

var work = {
    "jobs": [{
        "employer": "Kronos Canadian Systems Inc.",
        "title": "QA AUTOMATION INTERN",
        "location": "Montreal, QC",
        "dates": "Sept 16 - Present",
        "description": "Java programming for improving TestNG API automation framework;<br>Agile development of backend automation testing (REST API) under TestNG framework."
    }, {
        "employer": "BioMindR, TandemLaunch Inc.",
        "title": "SOFTWARE DEVELOPMENT INTERN",
        "location": "Montreal, QC",
        "dates": "June 16 - Sept 16",
        "description": "Python GUI by using PyQt, for converting, manipulating, and analyzing the data generated by Gnuradio-Companion;<br>Investigated the function of USRP board and achieved basic DSP in Gnuradio-Companion"
    }, {
        "employer": "Software Radio Lab, McGill University",
        "title": "RESEARCH STUDENT",
        "location": "Montreal, QC",
        "dates": "May 15 - Dec 15",
        "description": "Assisted research associates to implement wireless communication protocols;<br>Developed the software test tools using Visual Basic and performed functional and performance testing for various protocols of ESP8266 Module"
    }]
};

var projects = {
    "projects": [{
        "title": "Personal website",
        "dates": "Jan 2017",
        "description": "Created a website using HTML, CSS, JavaScript, jQuery, to exam the learning of web development",
        "images": ["./images/miao.png"],
        "link": "https://yan-ren.github.io/WebsiteDemo_Miaomiao"
    }, {
        "title": "OpenCV Face Recognition and Pose Estimation",
        "dates": "May 2016",
        "description": "Used OpenCV in C++, implemented Eigenfaces, Local Binary Pattern histograms and Bag of Visual Words for face recognition and pose estimation",
        "images": ["./images/opencv.jpg"],
        "link": "https://github.com/yan-ren"
    }]
};

function displayHeader() {
    var formattedName = HTMLheaderName.replace("%data%", bio.name);
    var formattedRole = HTMLheaderRole.replace("%data%", bio.role);
    var formattedImage = HTMLbioPic.replace("%data%", bio.bioPic);
    var formattedEmail = HTMLemail.replace("%data%", bio.contacts.email);
    var formattedLocation = HTMLlocation.replace("%data%", bio.contacts.location);
    var formattedGithub = HTMLgithub.replace("%data%", "<a class=\"\" href=\"" + bio.contacts.github + "\" target=\"_blank\">" + "yan-ren" + "</a>");
    var formattedLinkedin = HTMLlinkedin.replace("%data%", "<a class=\"\" href=\"" + bio.contacts.linkedin + "\" target=\"_blank\">" + "Yan Ren" + "</a>");
    var downloadResume = '<li class="flex-item"><span class="orange-text"></span><span class="white-text"><a class="" href="./resume.html" target="_self">View in PDF</a></span></li>';
    $("#header").prepend(formattedRole).prepend(formattedName).append(formattedImage);
    $("#topContacts").append(formattedLocation);
    $("#topContacts").append(formattedEmail);
    $("#topContacts").append(formattedGithub);
    $("#topContacts").append(formattedLinkedin);
      $("#topContacts").append(downloadResume);
    $("#header").append(HTMLskillsStart);
    if (bio.skills.length > 0) {
        bio.skills.forEach(function(skill) {
            $("#skills").append(HTMLskills.replace("%data%", skill));
        });
    }
    $("#footerContacts").append(formattedEmail, formattedLinkedin);
};
displayHeader();

function displayWork() {
    work.jobs.forEach(function(job) {
        $("#workExperience").append(HTMLworkStart);
        var formattedEmployer = HTMLworkEmployer.replace("%data%", job.employer);
        var formattedTitle = HTMLworkTitle.replace("%data%", job.title);
        $(".work-entry:last").append(formattedEmployer + formattedTitle);
        $(".work-entry:last").append(HTMLworkDates.replace("%data%", job.dates));
        $(".work-entry:last").append(HTMLworkDescription.replace("%data%", job.description));
    });
}
displayWork();

projects.display = function() {
    projects.projects.forEach(function(project) {
        $("#projects").append(HTMLprojectStart);
        var formattedTitle = HTMLprojectTitle.replace("%data%", project.title);
			  formattedTitle = formattedTitle.replace("#", project.link);
        $(".project-entry:last").append(formattedTitle);
        var formattedDates = HTMLprojectDates.replace("%data%", project.dates);
        $(".project-entry:last").append(formattedDates);
        var formattedDescription = HTMLprojectDescription.replace("%data%", project.description);
        $(".project-entry:last").append(formattedDescription);
        if (project.images.length > 0) {
            project.images.forEach(function(image) {
                var formattedImage = HTMLprojectImage.replace("%data%", image);
                $(".project-entry:last").append(formattedImage);
            });
        }
    });
};

education.display = function() {
    education.schools.forEach(function(school) {
        $("#education").append(HTMLschoolStart);
        var formattedName = HTMLschoolName.replace("%data%", school.name);
        var formattedDegree = HTMLschoolDegree.replace("%data%", school.degree);
        var formattedDates = HTMLschoolDates.replace("%data%", school.dates);
        var formattedLocation = HTMLschoolLocation.replace("%data%", school.location);
        var formattedMajor = HTMLschoolMajor.replace("%data%", school.majors);
        $(".education-entry:last").append(formattedName + formattedDegree, formattedDates, formattedLocation, formattedMajor);
      });
    // if (education.onlineCourses.length > 0) {
    //     $(".education-entry:last").append(HTMLonlineClasses);
    //     education.onlineCourses.forEach(function(onlineCourse) {
    //         var formattedTitle = HTMLonlineTitle.replace("%data%", onlineCourse.title);
    //         var formattedSchool = HTMLonlineSchool.replace("%data%", onlineCourse.school);
    //         var formattedDates = HTMLonlineDates.replace("%data%", onlineCourse.dates);
    //         var formattedUrl = HTMLonlineURL.replace("%data%", onlineCourse.url);
    //         $(".education-entry:last").append(formattedTitle + formattedSchool, formattedDates, formattedUrl);
    //     });
    // }
};
function embedGame(){
	var HTMLgame = '<ul id="game" class="flex-column">'
                +'<li class="flex-item"><iframe src="./game/ball_drop.html" id="myIframe" width=580px height=230px frameborder="0" scrolling="no"><p>Your browser does not support iframes.</p></iframe></li>'
                // +'<li class="flex-item"><span class="white-text">Use keyboard xxx for play</span></li>'
                +'</ul>';
	var topContacts = document.getElementById('topContacts').offsetWidth;
	console.log(topContacts);
	var skills = document.getElementById('skills').offsetWidth;
	console.log(skills);
	var biopic = document.getElementById('biopic').offsetWidth;
	console.log(biopic);
	var gameWidth = topContacts - skills - biopic;
	console.log(gameWidth);
	$("#header").append(HTMLgame);
	var iframe = parent.document.getElementById("myIframe");
	iframe.width = gameWidth.toString();
}

embedGame();
education.display();
projects.display();
$("#mapDiv").append(googleMap);
